<html>
<head>

<!--#include file="../meta.inc" -->

<title>Brett Bauer's Extreme Car Audio</title>

<style type="text/css">
	A:hover { color:#ff0000; }
	A:link { text-decoration: none; }
	A:active { text-decoration: none; }
	A:visited { text-decoration: none; }
</style>

</head>

<body bgcolor="#FFFFFF" link="#771100" vlink="#330000" alink="#6699CC" leftmargin=0 topmargin=0>

<table border="0" cellspacing="0" cellpadding="0" width="100%">
<tr>
	<td colspan=2 valign="top"><img src="../graphics/sidebar_top.gif" width=281 height=68 alt="" border="0"></td>
<tr>
	<td valign="top"><img src="../graphics/sidebar_side.gif" width=128 height=168 alt="" border="0">
	<br>
	<center>
	<font face="Tahoma, Arial, Helvetica" size=4><b>
	<a href="../">Home</a><br>
	<a href="../tour/">Tour</a>
	</b></font>
	</center>
	</td>
	<td valign="top">


