</table><img src="../graphics/sidebar_top.gif" width=281 height=68></td>
<tr>
	<td valign="top" width="128"><img src="../graphics/sidebar_side.gif" width=128 height=168 alt="" border="0">
	<br>
	<center>
	<font face="Tahoma, Arial, Helvetica" size=4><b>
	<a href="../">Home</a><br>
	<a href="../tour/">Tour</a>
	<p>
	<a href="mailto:BrettBauer@turbonet.com">Contact<br>Brett</a>
	</b>
	<p>
	<font size=1>
	Original text<br>and images are<br>Copyright &copy; 1999<br>Brett Bauer
	</font>
	</font>
	</center>
	</td>
	<td valign="top">


